apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "todolist.fullname" . }}-{{ .Values.names.api }}
  labels:
    {{- include "todolist.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  replicas: {{ .Values.replicaCount.api }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: {{ include "todolist.name" . }}
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: {{ include "todolist.name" . }}
        app.kubernetes.io/component: api
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z {{ include "todolist.fullname" . }}-{{ .Values.env.mysqlHost }} 3306;
              do echo "waiting for database at {{ include "todolist.fullname" . }}-{{ .Values.env.mysqlHost }}";
              sleep 2;
              done;
      containers:
        - name: api
          image: {{ .Values.api.image }}
          ports:
            - containerPort: {{ .Values.api.port }}
          env:
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ include "todolist.fullname" . }}-config
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "todolist.fullname" . }}-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ include "todolist.fullname" . }}-config
                  key: MYSQL_DB
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "todolist.fullname" . }}-config
                  key: MYSQL_HOST
            - name: MYSQL_TABLE
              value: {{ .Values.api.mysqlTable | quote }}
            - name: PORT
              value: {{ .Values.api.port | toString | quote }}

          livenessProbe:
            httpGet:
              path: /livez
              port: {{ .Values.api.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.api.port }}
            initialDelaySeconds: 5
            periodSeconds: 10