apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" (include "todolist.fullname" .) .Values.names.frontend }}
  labels:
    {{- include "todolist.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: frontend
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z {{ printf "%s-%s" (include "todolist.fullname" .) .Values.names.backend }} {{ .Values.mariadb.port }};
              do echo waiting for database;
              sleep 2;
              done;
      containers:
        - name: todolist
          image: {{ .Values.todolist.image }}
          ports:
            - containerPort: {{ .Values.todolist.port }}
          envFrom:
            - configMapRef:
                name: {{ include "todolist.fullname" . }}-config
          env:
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "todolist.fullname" . }}-secret
                  key: MYSQL_PASSWORD

          livenessProbe:
            httpGet:
              path: /livez
              port: {{ .Values.todolist.port }}
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.todolist.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
