apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" (include "todolist.fullname" .) .Values.names.frontend }}
  labels:
    {{- include "todolist.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount.todolist }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: frontend
    spec:
      initContainers:
        - name: wait-for-api
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z {{ include "todolist.fullname" . }}-{{ .Values.names.api }} {{ .Values.api.port }};
              do echo "waiting for api at {{ include "todolist.fullname" . }}-{{ .Values.names.api }}";
              sleep 2;
              done;
      containers:
        - name: todolist
          image: {{ .Values.todolist.image }}
          resources:
            requests:
              cpu: "100m"     
              memory: "128Mi"
            limits:
              cpu: "500m"      
              memory: "256Mi"  
          ports:
            - containerPort: {{ .Values.todolist.port }}
          envFrom:
            - configMapRef:
                name: {{ include "todolist.fullname" . }}-config
          env:
            - name: API_BASE_URL
              value: {{ .Values.env.apiBaseUrl | quote }}

          livenessProbe:
            httpGet:
              path: /livez
              port: {{ .Values.todolist.port }}
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.todolist.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3