{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "todolist.fullname" . }}-ingress
  labels:
    {{- include "todolist.labels" . | nindent 4 }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    {{- if .Values.ingress.host }}
    - host: {{ .Values.ingress.host | quote }}
      http:
    {{- else }}
    - http:
    {{- end }}
        paths:
          # חשוב: ה-API חייב להופיע ראשון ברשימה
          - path: /todos
            pathType: Prefix
            backend:
              service:
                name: {{ include "todolist.fullname" . }}-{{ .Values.names.api }}
                port:
                  number: {{ .Values.api.port }}
          
          - path: /livez
            pathType: Prefix
            backend:
              service:
                name: {{ include "todolist.fullname" . }}-{{ .Values.names.api }}
                port:
                  number: {{ .Values.api.port }}

          # הפרונטנד תופס את כל השאר
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "todolist.fullname" . }}-{{ .Values.names.frontend }}
                port:
                  number: {{ .Values.todolist.port }}

          - path: /readyz
            pathType: Prefix
            backend:
              service:
                name: {{ include "todolist.fullname" . }}-{{ .Values.names.api }}
                port:
                  number: {{ .Values.api.port }}
{{- end }}