todolist:
  image: ghcr.io/bennyro-mta/todolist-vue:1.2
  port: 8080
  appUser: "Netanel Mirel"

mariadb:
  image: mariadb
  port: 3306
  storage: 1Gi

mysql:
  user: todo
  password: "abcdef"
  rootPassword: "" 

ingress:
  enabled: true
  className: nginx
  host: ""

names:
  frontend: frontend
  backend: backend
  api: todo-api    

api:
  image: ghcr.io/bennyro-mta/todos-api:1.2
  port: 8080
  mysqlTable: todos       

backup:
  enabled: true
  schedule: "0 2 * * *"
  image: alpine:3.19
  pvc:
    storageClassName: standard
    size: 5Gi
  inspector:
    enabled: true
    image: busybox:1.36

replicaCount:
  webui: 2
  api: 1
  todolist: 2

service:
  webuiType: LoadBalancer
  frontendType: LoadBalancer  
  apiType: ClusterIP           

env:
  user: "Netanel Mirel"      
  mysqlHost: backend       
  apiBaseUrl: "/todos"              
 
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50