names:
  frontend: frontend
  backend: backend

todolist:
  image: ghcr.io/bennyro-mta/todolist:1.10
  port: 5000
  appUser: "netanel"

mariadb:
  image: mariadb
  port: 3306
  storage: 1Gi

service:
  frontendType: ClusterIP

mysql:
  user: todo
  password: "abcdef"

backup:
  enabled: true
  schedule: "0 2 * * *"
  image: alpine:3.19
  pvc:
    storageClassName: standard
    size: 5Gi
  inspector:
    enabled: true
    image: busybox:1.36


autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50